### ISSUE TITLE
FromStrRadix::from_str_radix expects a Result now

### ISSUE THREAD

**Issue by brutal-chaos** [kimhyunkang/libyaml-rust#3]
79ed38c8041ce14564e6cc5a22468000e60aeb60 (v0.0.10) fails with:

    src/constructor.rs:128:9: 128:19 error: mismatched types:
     expected `core::result::Result<_, _>`,
        found `core::option::Option<_>`
    (expected enum `core::result::Result`,
        found enum `core::option::Option`) [E0308]
    src/constructor.rs:128         Some(code) if rep.len() == expected_len => char::from_u32(code),
                                   ^~~~~~~~~~
    error: aborting due to previous error
    Could not compile `yaml`.

**Comment by kimhyunkang** [comment]
It's fixed now. Thanks for reporting!
