### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by kerrickstaley** [kimhyunkang/libyaml-rust#5]
The build is failing; see https://travis-ci.org/kimhyunkang/libyaml-rust/builds/56370624

**Comment by kerrickstaley** [comment]
I think [this change](https://github.com/kerrickstaley/libyaml-rust/commit/d9ee95e7020e23df9c61766573711b09fcddc53c) is the first step. But there are [other errors](https://travis-ci.org/kerrickstaley/libyaml-rust/builds/57231605); not sure how to fix these.

**Comment by kimhyunkang** [comment]
It's fixed now. Thanks!

**Comment by kerrickstaley** [comment]
Could you push 0.1.4 to crates.io? Thanks!

**Comment by kimhyunkang** [comment]
It's up now. Thanks!
