### ISSUE TITLE
event positions

### ISSUE THREAD

**Issue by DenisCheremisov** [kimhyunkang/libyaml-rust#6]
Hi!
In my project (C++ currently) I am using yaml as configuration format and it is critical to be able to locate position of data that does not pass validation. I noticed rust event structs do not inherit positional information from c structs. May be to add it? I would implement structural parser once done, i.e. parser which expects some predifined structure on yaml data.

**Comment by kimhyunkang** [comment]
I added start / end markers to event structs: edf81ca

Due to the API change, I bumped the version to v0.2

Thanks!

**Comment by DenisCheremisov** [comment]
Great! Thank you!
